Repository Kelompok-8-alterra/LMS-Backend, pull requests merged in 2021-12, with the labels that each got.

#1 documentation(Swagger): add swagger API
  docs/Swagger Docs API.yaml
  go.mod
  go.sum
Labels: documentation

#3 feature (categories): add Get ALL categories
  .gitignore
  app/routes/route.go
  business/categories/domain.go
  business/categories/usecase.go
  config.json
  controllers/base_response.go
  controllers/categories/http.go
  controllers/categories/response/categories_response.go
  drivers/database/categories/mysql.go
  drivers/database/categories/record.go
  drivers/mysql/driver.go
  go.mod
  go.sum
  helpers/err/code.go
  helpers/err/error.go
  main.go
Labels: enhancement

#5 Feature/getallenroll
  app/routes/routes.go
  business/enrollments/domain.go
  business/enrollments/usecase.go
  controllers/enrollments/http.go
  controllers/enrollments/response/response.go
  drivers/database/enrollments/record.go
  drivers/database/enrollments/repository.go
  helper/err/code.go
  helper/err/error.go
  main.go
Labels: enhancement

#4 Feature/course : add Create Course
  app/middleware/auth.go
  app/routes/routes.go
  business/course/domain.go
  business/course/usecase.go
  config.json
  controllers/categories/http.go
  controllers/courses/http.go
  controllers/courses/request/add.go
  controllers/courses/response/add.go
  drivers/database/categories/repository.go
  drivers/database/course/record.go
  drivers/database/course/repository.go
  go.mod
  helper/err/code.go
  helper/err/error.go
  main.go
Labels: enhancement

#6 feature(GetAllCourse) : complete get all courses
  app/routes/routes.go
  business/course/domain.go
  business/course/usecase.go
  controllers/courses/http.go
  controllers/courses/response/add.go
  drivers/database/course/record.go
  drivers/database/course/repository.go
  helper/err/code.go
  helper/err/error.go
Labels: enhancement

#7 feature add enrollment
  app/routes/routes.go
  business/enrollments/domain.go
  business/enrollments/usecase.go
  business/student/usecase.go
  business/teacher/usecase.go
  config.json
  controllers/enrollments/http.go
  controllers/enrollments/request/request.go
  controllers/enrollments/response/response.go
  controllers/student/http.go
  controllers/student/request/request.go
  controllers/teacher/http.go
  controllers/teacher/request/request.go
  drivers/database/enrollments/record.go
  drivers/database/enrollments/repository.go
  drivers/database/student/repository.go
  drivers/database/teacher/repository.go
  helper/err/code.go
  helper/err/error.go
Labels: enhancement

#14 fixing main
  controllers/enrollments/response/response.go
  drivers/database/course/repository.go
Labels: bug

#15 Fix main
  helper/err/code.go
Labels: bug

#9 Feature/getallmodules
  app/routes/routes.go
  business/modules/domain.go
  business/modules/usecase.go
  controllers/modules/http.go
  controllers/modules/response/response.go
  drivers/database/enrollments/repository.go
  drivers/database/modules/record.go
  drivers/database/modules/repository.go
  helper/err/code.go
  main.go
Labels: enhancement

#12 Feature/addmodules
  app/routes/routes.go
  business/modules/domain.go
  business/modules/usecase.go
  business/teacher/domain.go
  business/teacher/usecase.go
  controllers/modules/http.go
  controllers/modules/request/request.go
  controllers/teacher/request/request.go
  controllers/teacher/response/response.go
  drivers/database/enrollments/repository.go
  drivers/database/modules/record.go
  drivers/database/modules/repository.go
  drivers/database/teacher/record.go
  helper/err/code.go
  helper/err/error.go
Labels: enhancement

#16 Feature/updatemodules
  app/routes/routes.go
  business/modules/domain.go
  business/modules/usecase.go
  controllers/modules/http.go
  controllers/modules/request/request.go
  drivers/database/modules/repository.go
  helper/err/code.go
Labels: enhancement

#17 Feature(modules)getbycourseid
  app/routes/routes.go
  business/modules/domain.go
  business/modules/usecase.go
  controllers/modules/http.go
  controllers/modules/request/request.go
  drivers/database/modules/repository.go
  helper/err/code.go
Labels: enhancement

#18 Feature/deletemodules
  app/routes/routes.go
  business/modules/domain.go
  business/modules/usecase.go
  controllers/modules/http.go
  drivers/database/modules/repository.go
  helper/err/code.go
Labels: enhancement

#19 Feature/updateenroll
  app/routes/routes.go
  business/enrollments/domain.go
  business/enrollments/usecase.go
  controllers/enrollments/http.go
  controllers/enrollments/request/request.go
  drivers/database/enrollments/repository.go
  helper/err/code.go
  helper/err/error.go
Labels: enhancement

#20 Feature/getbyidenroll
  app/routes/routes.go
  business/enrollments/domain.go
  business/enrollments/usecase.go
  controllers/enrollments/http.go
  controllers/modules/response/response.go
  drivers/database/enrollments/repository.go
  helper/err/code.go
Labels: enhancement

#22 feature(CORS): adding localhost allow origin
  config.json
  main.go
Labels: enhancement
