Repository Kelompok-8-alterra/LMS-Backend, pull requests merged in 2022-01, with the labels that each got.

#34 fix(updateTeacher): Make Password update not always required
  business/course/usecase_test.go
  business/teacher/domain.go
  business/teacher/usecase.go
  controllers/teacher/request/request.go
  controllers/teacher/response/response.go
  drivers/database/teacher/record.go
  drivers/database/teacher/repository.go
Labels: bug, enhancement

#37 fixed unit test
  business/course/usecase_test.go
  cover.out
Labels: bug

#39 fix(student): update Phone and Pass checked
  business/student/domain.go
  business/student/usecase.go
  controllers/student/request/request.go
  controllers/student/response/response.go
  drivers/database/student/record.go
Labels: bug, enhancement

#42 reading get by id
  app/routes/routes.go
  business/readings/domain.go
  business/readings/usecase.go
  config.json
  controllers/readings/http.go
  drivers/database/readings/repository.go
  helper/err/code.go
Labels: enhancement

#40 fix(updateStudent): change email check
  drivers/database/student/repository.go
Labels: bug, enhancement

#43 fix(passUpdate): student update pass
  business/student/usecase.go
Labels: bug

#47 feature(request): add id response
  controllers/requests/response/response.go
Labels: enhancement

#50 Unit testing all
  business/difficulties/mocks/Repository.go
  business/difficulties/usecase_test.go
  business/enrollments/mocks/EnrollmentsRepoInterface.go
  business/enrollments/usecase.go
  business/enrollments/usecase_test.go
  business/modules/mocks/ModulesRepoInterface.go
  business/modules/usecase_test.go
  business/readings/mocks/ReadingsRepoInterface.go
  business/readings/usecase.go
  business/readings/usecase_test.go
  business/requests/mocks/RequestsRepoInterface.go
  business/requests/usecase_test.go
  business/student/mocks/StudentRepoInterface.go
  business/student/usecase_test.go
  business/teacher/mocks/TeacherRepoInterface.go
  business/teacher/usecase_test.go
  business/types/mocks/Repository.go
  business/types/usecase_test.go
  business/videos/mocks/VideosRepoInterface.go
  business/videos/usecase_test.go
  cover.out
Labels: enhancement

#52 allow FE app to connect
  cover.out
  main.go
Labels: enhancement

#53 UnitTest(course): add course unit testing
  business/course/cover
  business/course/mocks/Repository.go
  business/course/usecase_test.go
  cover
  cover.html
  helper/err/error.go
Labels: enhancement
